# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#title: Trauma Recovery Services
#description: >- 
#  Trauma Recovery Services provides counseling and assessment to improve the mental health and well-being of children, adolescents and families. 
email: info@traumarecoveryservices.org
email_display: info@&#8203;traumarecoveryservices.org
phone: "505-633-8001"
fax: "505-884-0222"
address: >-
  6121 Indian School Road<br/>
  Suite 235<br/>
  Albuquerque, NM 87110
url: "https://traumarecoveryservices.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_handle: TRS_TW
instagram_handle: TRS_IN
facebook_handle: TRS_FB
google_analytics: "UA-145104919-1"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - README.md
  - .DS_Store

# Include into processing.
include: 
  - _redirects